services:
  # React Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: task-generator-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - task-generator-network
    restart: unless-stopped

  # Python Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: task-generator-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
    volumes:
      - uploads_data:/app/uploads
      - temp_data:/tmp
    networks:
      - task-generator-network
    restart: unless-stopped

networks:
  task-generator-network:
    driver: bridge

volumes:
  uploads_data:
  temp_data:

